# Generated by Django 4.2.7 on 2023-12-08 15:34

from django.db import migrations, models
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('author', models.CharField(max_length=16, verbose_name='作者')),
                ('category', models.CharField(default='其他', max_length=10, verbose_name='分类')),
                ('body', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布日期')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('mod_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('pub', '发布')], default='draft', max_length=8, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='UserIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=20, verbose_name='用户ip')),
                ('serial_number', models.CharField(default=0, max_length=10, verbose_name='访问序号')),
                ('access_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='首次访问时间')),
                ('ip_attribution', models.CharField(default='', max_length=64, verbose_name='ip地址')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='日期')),
                ('visits', models.IntegerField(default=0, verbose_name='访问量')),
            ],
        ),
    ]
