# Generated by Django 4.2.7 on 2023-12-11 08:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='latest_viewing_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最新查看日期'),
        ),
        migrations.AddField(
            model_name='article',
            name='latest_viewing_user',
            field=models.CharField(default='', max_length=16, verbose_name='最新查看用户'),
        ),
    ]
