# Generated by Django 4.2.7 on 2023-12-13 18:37

from django.db import migrations, models
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_article_latest_viewing_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=16, verbose_name='作者')),
                ('email', models.CharField(default='', max_length=64, verbose_name='邮箱')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('sub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('ip', models.CharField(default='', max_length=16, verbose_name='用户IP')),
                ('ip_attribution', models.CharField(default='', max_length=64, verbose_name='IP地址')),
            ],
        ),
    ]
