# Generated by Django 4.2.7 on 2023-12-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_comment_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='用户IP'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ip_attribution',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='IP地址'),
        ),
    ]
