# Generated by Django 4.2.7 on 2023-12-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_comment_email_alter_comment_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='删除'),
        ),
    ]
