# Generated by Django 4.2.7 on 2023-12-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_rename_aboutsite_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='first_viewing_ip',
            field=models.CharField(default='', max_length=16, verbose_name='首次访问ip'),
        ),
        migrations.AddField(
            model_name='visit',
            name='latest_viewing_ip',
            field=models.CharField(default='', max_length=16, verbose_name='最新访问ip'),
        ),
    ]
