# Generated by Django 4.2.7 on 2024-06-20 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_visit_first_viewing_ip_visit_latest_viewing_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, verbose_name='文件名')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传日期')),
                ('downloads', models.IntegerField(default=0, verbose_name='下载数')),
            ],
        ),
    ]
