# Generated by Django 4.2.7 on 2024-07-30 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=16, unique=True, verbose_name='作者')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('delete', models.BooleanField(default=False, verbose_name='删除')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=16, unique=True, verbose_name='分类')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('delete', models.BooleanField(default=False, verbose_name='删除')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=16, unique=True, verbose_name='Status')),
                ('name_cn', models.CharField(default='', max_length=16, unique=True, verbose_name='状态')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('delete', models.BooleanField(default=False, verbose_name='删除')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='state',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(default='', max_length=8, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='', max_length=16, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(default='', max_length=10, verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='_author',
            field=models.ForeignKey(limit_choices_to={'delete': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.author', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='article',
            name='_category',
            field=models.ForeignKey(limit_choices_to={'delete': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='_status',
            field=models.ForeignKey(limit_choices_to={'delete': False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.status', verbose_name='状态'),
        ),
    ]
